language: c

branches:
  only:
    - master
    - release

dist: trusty
sudo: required

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=debug
        - CC1=gcc-6
        - CXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=release
        - CC1=gcc-6
        - CXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
        - CC1=gcc-6
        - CXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=release
        - CC1=gcc-6
        - CXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=debug
        - CC1=gcc-6
        - CXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - FAVORITE_CONFIG=yes
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - CC1=gcc-6
        - CXX1=g++-6

    - os: osx
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=debug
        - CC1=clang-3.7
        - CXX1=clang++-3.7

    - os: osx
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=release
        - lto=no
        - CC1=clang-3.7
        - CXX1=clang++-3.7

    - os: osx
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
        - CC1=clang-3.8
        - CXX1=clang++-3.8

    - os: osx
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=release
        - lto=no
        - CC1=clang-3.8
        - CXX1=clang++-3.8

    - os: osx
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=debug
        - CC1=clang-3.9
        - CXX1=clang++-3.9

    - os: osx
      env:
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - lto=no
        - CC1=clang-3.9
        - CXX1=clang++-3.9

rvm:
  - 2.2.3

install:
  - bash .travis_install.bash

script:
  - bash .travis_script.bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - buildbot@lists.ponylang.org

deploy:
  - provider: bintray
    user: pony-buildbot-2
    file: /home/travis/build/ponylang/ponyc/bintray_debian.json
    on:
      branch: release
      condition: "$FAVORITE_CONFIG == yes"

    key:
      secure: "GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8="

  - provider: bintray
    user: pony-buildbot-2
    file: /home/travis/build/ponylang/ponyc/bintray_rpm.json
    on:
      branch: release
      condition: "$FAVORITE_CONFIG == yes"
    key:
      secure: "GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8="

  - provider: bintray
    user: pony-buildbot-2
    file: /home/travis/build/ponylang/ponyc/bintray_source.json
    on:
      branch: release
      condition: "$FAVORITE_CONFIG == yes"
    key:
      secure: "GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8="

