language: c

branches:
  only:
    - master

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      env:
        - LLVM_VERSION="3.6.2"
        - LLVM_CONFIG="llvm-config-3.6"
        - config=debug
    - os: linux
      env:
        - LLVM_VERSION="3.6.2"
        - LLVM_CONFIG="llvm-config-3.6"
        - config=release
    - os: linux
      env:
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=debug
    - os: linux
      env:
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=release
    - os: linux
      env:
        - LLVM_VERSION="3.8.0"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
    - os: linux
      env:
        - LLVM_VERSION="3.8.0"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=release
    - os: osx
      env:
        - LLVM_CONFIG="llvm-config-3.6"
        - config=debug
    - os: osx
      env:
        - LLVM_CONFIG="llvm-config-3.6"
        - config=release
    - os: osx
      env:
        - LLVM_CONFIG="llvm-config-3.7"
        - config=debug
    - os: osx
      env:
        - LLVM_CONFIG="llvm-config-3.7"
        - config=release
    - os: osx
      env:
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
    - os: osx
      env:
        - LLVM_CONFIG="llvm-config-3.8"
        - config=release

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ];
    then
      wget "http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz";
      tar -xvf clang+llvm*;
      cd clang+llvm* && sudo mkdir /tmp/llvm && sudo cp -r * /tmp/llvm/;
      sudo ln -s /tmp/llvm/bin/llvm-config /usr/local/bin/${LLVM_CONFIG};
      cd -;
      wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.21.tar.bz2;
      tar -xjvf pcre2-10.21.tar.bz2;
      cd pcre2-10.21 && ./configure --prefix=/usr && make && sudo make install;
      cd -;
    fi;
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];
    then
      brew update;
      brew install llvm36 llvm37 llvm38 pcre2 libressl;
    fi;

script:
  - make test

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - buildbot@lists.ponylang.org

deploy:
  - provider: bintray
    user: pony-buildbot
    file: bintray_debian.yml
    on:
      branch: release
      condition: $UPLOAD = yes
    key:
      secure: lHcuHpEj2N/P5SajENhVOT+mH1pwlInlBfk0l09fUuvoqLAIJI6Gb1OHGbNnazxxxH/ANVmP14XIU8hGWwQBGMTjUkJ8/FyyzGCHJlMiSSBzdAozLp1rG4A5IaNg9KvHgwljjerGp1FcTDjySV7v+I4eouhIravc6223xOrpPIQo8U0ZXm6vIIP4g8CVqMzBBsJh6O79GiGceV9x4G1nky40Tf1ulA0BmDiv1k1NEjMQKq04PX/OzQSSF/eHeVXOHFVmbz7dwngKtdMoZodsZDLfSJgG7aCH7k6opg0M+OkitB+RHR7O8cpPcbbOVuJTYcbiKeHvctN2yVXXiwNiawuGGw6M2ik+fSqrPg5POr+vbbXruGlr55ZmTP1WMbF750heKjNsSvrSAdsdquCv3vVvAbBykVO0cDrYWrMnik7cbT5nzFSwrZYiQorKC6HrBHQ6LFaK4hKNh0xVPu8WTCmWQBGtDjpEIlKDuLH2A0K3mz+DJGgn4Y+TIHJeKwp6yPZTaa6h+w0afDmA9cHzG73mp8S9u1NIc4P2HObIdkTnvb/5EoQ0r+46uPVETmRnspxlYZYPg/76jrrRTeAfEj8OI57IeRi2Yxa5iUyiA6/Pe/Kyfxkly8fV/JBQYjgDKmB9zUjKT7RAvSk1adSL69+PKWeU6Y6zYrz+c92CMGA=
  - provider: bintray
    user: pony-buildbot
    file: bintray_rpm.yml
    on:
      branch: release
      condition: $UPLOAD = yes
    key:
      secure: lHcuHpEj2N/P5SajENhVOT+mH1pwlInlBfk0l09fUuvoqLAIJI6Gb1OHGbNnazxxxH/ANVmP14XIU8hGWwQBGMTjUkJ8/FyyzGCHJlMiSSBzdAozLp1rG4A5IaNg9KvHgwljjerGp1FcTDjySV7v+I4eouhIravc6223xOrpPIQo8U0ZXm6vIIP4g8CVqMzBBsJh6O79GiGceV9x4G1nky40Tf1ulA0BmDiv1k1NEjMQKq04PX/OzQSSF/eHeVXOHFVmbz7dwngKtdMoZodsZDLfSJgG7aCH7k6opg0M+OkitB+RHR7O8cpPcbbOVuJTYcbiKeHvctN2yVXXiwNiawuGGw6M2ik+fSqrPg5POr+vbbXruGlr55ZmTP1WMbF750heKjNsSvrSAdsdquCv3vVvAbBykVO0cDrYWrMnik7cbT5nzFSwrZYiQorKC6HrBHQ6LFaK4hKNh0xVPu8WTCmWQBGtDjpEIlKDuLH2A0K3mz+DJGgn4Y+TIHJeKwp6yPZTaa6h+w0afDmA9cHzG73mp8S9u1NIc4P2HObIdkTnvb/5EoQ0r+46uPVETmRnspxlYZYPg/76jrrRTeAfEj8OI57IeRi2Yxa5iUyiA6/Pe/Kyfxkly8fV/JBQYjgDKmB9zUjKT7RAvSk1adSL69+PKWeU6Y6zYrz+c92CMGA=
  - provider: bintray
    user: pony-buildbot
    file: bintray_source.yml
    on:
      branch: release
      condition: $UPLOAD = yes
    key:
      secure: lHcuHpEj2N/P5SajENhVOT+mH1pwlInlBfk0l09fUuvoqLAIJI6Gb1OHGbNnazxxxH/ANVmP14XIU8hGWwQBGMTjUkJ8/FyyzGCHJlMiSSBzdAozLp1rG4A5IaNg9KvHgwljjerGp1FcTDjySV7v+I4eouhIravc6223xOrpPIQo8U0ZXm6vIIP4g8CVqMzBBsJh6O79GiGceV9x4G1nky40Tf1ulA0BmDiv1k1NEjMQKq04PX/OzQSSF/eHeVXOHFVmbz7dwngKtdMoZodsZDLfSJgG7aCH7k6opg0M+OkitB+RHR7O8cpPcbbOVuJTYcbiKeHvctN2yVXXiwNiawuGGw6M2ik+fSqrPg5POr+vbbXruGlr55ZmTP1WMbF750heKjNsSvrSAdsdquCv3vVvAbBykVO0cDrYWrMnik7cbT5nzFSwrZYiQorKC6HrBHQ6LFaK4hKNh0xVPu8WTCmWQBGtDjpEIlKDuLH2A0K3mz+DJGgn4Y+TIHJeKwp6yPZTaa6h+w0afDmA9cHzG73mp8S9u1NIc4P2HObIdkTnvb/5EoQ0r+46uPVETmRnspxlYZYPg/76jrrRTeAfEj8OI57IeRi2Yxa5iUyiA6/Pe/Kyfxkly8fV/JBQYjgDKmB9zUjKT7RAvSk1adSL69+PKWeU6Y6zYrz+c92CMGA=

after_success:
  - if [[ $TRAVIS_OSNAME == "linux" && $CC == "gcc" && $TRAVIS_BRANCH == "release" ]];
    then
      cat VERSION | xargs sh .bintray.sh debian $1;
      cat VERSION | xargs sh .bintray.sh rpm $1;
      cat VERSION | xargs sh .bintray.sh source $1;
      make config=release deploy;
      export UPLOAD=yes;
    fi;
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
      git remote add gh-token "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}";
      git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
      build/release/ponyc packages/stdlib --docs;
      cd stdlib-docs;
      sudo -H pip install mkdocs;
      sed -i '' 's/site_name:\ stdlib/site_name:\ Pony Standard Library/' mkdocs.yml;
      mkdocs gh-deploy -v --clean --remote-name gh-token;
    fi;
