language: 
  - c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list;
      echo "deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list;
      echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list;
      echo "deb-src http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list;
      sudo apt-get update -qq;
      sudo apt-get -y --force-yes -qq install libllvm3.6 llvm-3.6 llvm-3.6-dev;

      if [[ "$CC" == "clang" ]]; then
        sudo apt-get -y --force-yes -qq install clang-3.6 && export CC=clang-3.6 && export CXX=clang++-3.6;
      elif [[ "$CC" == "gcc" ]]; then
        sudo apt-get -y --force-yes -qq install gcc-4.9 g++-4.9 && export CC=gcc-4.9 && export CXX=g++-4.9;
      fi

      wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.20.tar.bz2;
      tar -xjvf pcre2-10.20.tar.bz2;
      cd pcre2-10.20 && ./configure --prefix=/usr && make && sudo make install;
      cd -;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install -v llvm --with-rtti;
      brew install pcre2 libressl;
    fi

script: make test && make config=release test

cache:
  directories:
  - /usr/local/Cellar/llvm

notifications:
  irc: 
    channels:
      - "chat.freenode.net#ponylang"
    template:
      - "%{repository} (%{commit}) : %{message} (%{author}) : %{result}"


