language: c
branches:
  only:
  - master
  - release
dist: trusty
sudo: required
services:
- docker

# NOTE: This holds fedora COPR API related variables. Unfortunately, the values expire every 180 days.
# As a result, we have to remember to visit https://copr.fedorainfracloud.org/api/ and generate a new token
# and then run the following to update variables and replace the "secure" value.
# travis encrypt COPR_LOGIN=VALUE COPR_TOKEN=VALUE --org -r ponylang/ponyc

env:
  global:
  - secure: iARfP1hIHukdK7u9mNNtbyfZVWMO/mnqQiEPTGnQyDBWykIFAe8fHnOhU+Wc982dJoWDcS1rR1UMZl++SRtzDgg6qmBqWou8Dqxv/kmmVTHy8mCx6xbG443ihRXo8AGW1SyQVWuOVMosDugMAqjRC1kX99IVrPNSkTgC+XjikzjCq75Ay89LMtA0lzT2kf2ijdthbVi/e1MkwLSBgcyr3QCbVGFadzavxDfULCslhmuhqd+q8f+bbsL5FZF07ZnKJCtxx+WjeNLfgK0GWH3Ds9CJM0JcBqn2Lg65oT8ywJ7Xk5WbJFvgqHO8gHmo7iyVuFF81ZyKKun/yIL7v8P4pSAkO+3L4Er9+Wcg4sddG6UkC5b5PTrvdgdVT3YVVxEWa1sTwlBbb6a0eDQ0HPmG/BJwqJTbwPYdMaUmx4kKN5sfaMpqcxLH732JUdC4ty0nmeBqWPlnQzsyM5IoW5gi3mS5ITYEr3I1c3MRtI+FJbFstij8IlNGJJqZSvM7CATkX6PWfiXoQDKXMn5o4Dd0kstNE5oV5N3KVjXvRfQsLE3pqp1wCCcsc8kOS4QAaJ2nVPArgS9XNUa5UGtqjpP+f3HbZun8FwCjPdzKBP8tAnXVOAzhmcI9fp9UajJaK03xyk6dVEy81V9wLDyU2zj61vC46aj6ejmIeYkZrSExPWg=
  - CROSS_ARCH=
  - VAGRANT_ENV=
  - RELEASE_CONFIG=no
  - RELEASE_DEBS=
  - CC1=gcc
  - CXX1=g++
  - ICC1=gcc-6
  - ICXX1=g++-6
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - RELEASE_CONFIG=yes
    - LLVM_VERSION="7.0.1"
    - LLVM_CONFIG="llvm-config-7.0"
    - config=release
  - os: linux
    env:
    - RELEASE_CONFIG=yes
    - RELEASE_DEBS=ubuntu
  - os: linux
    env:
    - RELEASE_CONFIG=yes
    - RELEASE_DEBS=debian
  - os: linux
    env:
    - DOCKER_ARCH=i686
    - CROSS_ARCH=i686
    - LLVM_VERSION="3.9.1"
    - LLVM_CONFIG="llvm-config-3.9"
    - config=debug
    - CROSS_CFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_CXXFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_LDFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_BITS=32
    - CROSS_TRIPLE=i686-unknown-linux-gnu
    - CROSS_LINKER='gcc-6 -m32'
    - CROSS_CC=gcc-6
    - CROSS_CXX=g++-6
    - CROSS_TUNE=generic
  - os: linux
    env:
    - DOCKER_ARCH=i686
    - CROSS_ARCH=i686
    - LLVM_VERSION="3.9.1"
    - LLVM_CONFIG="llvm-config-3.9"
    - config=release
    - CROSS_CFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_CXXFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_LDFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_BITS=32
    - CROSS_TRIPLE=i686-unknown-linux-gnu
    - CROSS_LINKER='gcc-6 -m32'
    - CROSS_CC=gcc-6
    - CROSS_CXX=g++-6
    - CROSS_TUNE=generic
  - os: linux
    env:
    - DOCKER_ARCH=aarch64
    - CROSS_ARCH=armv8-a
    - LLVM_VERSION="6.0.0"
    - LLVM_CONFIG="llvm-config-6.0"
    - config=debug
    - CROSS_CFLAGS='-idirafter /usr/cross/include/'
    - CROSS_CXXFLAGS='-idirafter /usr/cross/include/'
    - CROSS_LDFLAGS='-idirafter /usr/cross/include/'
    - CROSS_BITS=64
    - CROSS_TRIPLE=aarch64-unknown-linux-gnu
    - CROSS_LINKER=aarch64-linux-gnu-gcc
    - CROSS_CC=aarch64-linux-gnu-gcc
    - CROSS_CXX=aarch64-linux-gnu-g++
    - QEMU_RUNNER='qemu-aarch64-static --cpu cortex-a53 -L /usr/local/aarch64-linux-gnu/libc'
    - CROSS_TUNE=cortex-a53
  - os: linux
    env:
    - DOCKER_ARCH=aarch64
    - CROSS_ARCH=armv8-a
    - LLVM_VERSION="6.0.0"
    - LLVM_CONFIG="llvm-config-6.0"
    - config=release
    - CROSS_CFLAGS='-idirafter /usr/cross/include/'
    - CROSS_CXXFLAGS='-idirafter /usr/cross/include/'
    - CROSS_LDFLAGS='-idirafter /usr/cross/include/'
    - CROSS_BITS=64
    - CROSS_TRIPLE=aarch64-unknown-linux-gnu
    - CROSS_LINKER=aarch64-linux-gnu-gcc
    - CROSS_CC=aarch64-linux-gnu-gcc
    - CROSS_CXX=aarch64-linux-gnu-g++
    - QEMU_RUNNER='qemu-aarch64-static --cpu cortex-a53 -L /usr/local/aarch64-linux-gnu/libc'
    - CROSS_TUNE=cortex-a53
  allow_failures:
  - os: linux
    env:
    - DOCKER_ARCH=i686
    - CROSS_ARCH=i686
    - LLVM_VERSION="3.9.1"
    - LLVM_CONFIG="llvm-config-3.9"
    - config=debug
    - CROSS_CFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_CXXFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_LDFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_BITS=32
    - CROSS_TRIPLE=i686-unknown-linux-gnu
    - CROSS_LINKER='gcc-6 -m32'
    - CROSS_CC=gcc-6
    - CROSS_CXX=g++-6
    - CROSS_TUNE=generic
  - os: linux
    env:
    - DOCKER_ARCH=i686
    - CROSS_ARCH=i686
    - LLVM_VERSION="3.9.1"
    - LLVM_CONFIG="llvm-config-3.9"
    - config=release
    - CROSS_CFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_CXXFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_LDFLAGS='-m32 -idirafter /usr/cross/include/'
    - CROSS_BITS=32
    - CROSS_TRIPLE=i686-unknown-linux-gnu
    - CROSS_LINKER='gcc-6 -m32'
    - CROSS_CC=gcc-6
    - CROSS_CXX=g++-6
    - CROSS_TUNE=generic
  - os: linux
    env:
    - DOCKER_ARCH=aarch64
    - CROSS_ARCH=armv8-a
    - LLVM_VERSION="6.0.0"
    - LLVM_CONFIG="llvm-config-6.0"
    - config=debug
    - CROSS_CFLAGS='-idirafter /usr/cross/include/'
    - CROSS_CXXFLAGS='-idirafter /usr/cross/include/'
    - CROSS_LDFLAGS='-idirafter /usr/cross/include/'
    - CROSS_BITS=64
    - CROSS_TRIPLE=aarch64-unknown-linux-gnu
    - CROSS_LINKER=aarch64-linux-gnu-gcc
    - CROSS_CC=aarch64-linux-gnu-gcc
    - CROSS_CXX=aarch64-linux-gnu-g++
    - QEMU_RUNNER='qemu-aarch64-static --cpu cortex-a53 -L /usr/local/aarch64-linux-gnu/libc'
    - CROSS_TUNE=cortex-a53
  - os: linux
    env:
    - DOCKER_ARCH=aarch64
    - CROSS_ARCH=armv8-a
    - LLVM_VERSION="6.0.0"
    - LLVM_CONFIG="llvm-config-6.0"
    - config=release
    - CROSS_CFLAGS='-idirafter /usr/cross/include/'
    - CROSS_CXXFLAGS='-idirafter /usr/cross/include/'
    - CROSS_LDFLAGS='-idirafter /usr/cross/include/'
    - CROSS_BITS=64
    - CROSS_TRIPLE=aarch64-unknown-linux-gnu
    - CROSS_LINKER=aarch64-linux-gnu-gcc
    - CROSS_CC=aarch64-linux-gnu-gcc
    - CROSS_CXX=aarch64-linux-gnu-g++
    - QEMU_RUNNER='qemu-aarch64-static --cpu cortex-a53 -L /usr/local/aarch64-linux-gnu/libc'
    - CROSS_TUNE=cortex-a53
rvm:
- 2.2.3
script:
- bash .travis_script.bash
notifications:
  email: false
  webhooks:
    urls:
      - secure: IYtNjqplhXhwZqzUuuVn52fNBt2mToTLZBOM2v4ivC2HgaRr8F3w+TYd4/PBJ8Hr3KgFcDUOrICmbFhJK3N+Z8GiZ4xdxIe8Xkq6GERm3S9LYqd8j5mToZrf4vgrozDap9U0I4ZO+1+1jwGxIXLDHAkRy/XqucxJE67jxWlMbiHAF6z+eivkIbTCv5uso+fWLSu8rRmEvpm+tQFt9VVrr7KvlmB0OLMe4iQZy1OwF6FpcKsPiFDHZfKDKgZAikdg/IFRjnLvcqLxOuoWKbh5oOt6sC6V1S7943TgVHmESeSi/C/bvEvegaxfL4BhOyzIkCwD4USzAYRqFmdAwVw9l/gIsRDHK1HdvvqPGUJnFec0RO7A4Yzj9uIyi525+33qUOlP1f0MpGTwYw+ryqiORjv8Ry3SJzO7eSCpT0RvPZRRKd6egkgdIBhp4OUnbngkkKb4/z3WfjVB+ba5chYpFRosLkhUJM80AkRN0Q9ih0OefglJgKOk2IR5R8AQ8ezfnCl3FyBIjusruckSCzGtKzeh5rgxFWD0U3+x+bxb+ajLBD1TUVEP/wKukya/cLqz7TaXOrTtmHV/VN8PCj1v/fbrGnwAqVvKNY9x4K5SZh1gtCVujSuGrGZDLo2dosSRFKagUhg/STMSKQp+SR5ofC3NKuYMmd3HFYCLrhVVl6Q=
    on_success: always
    on_failure: always
  slack:
    rooms:
      - secure: Ojrqq/3nlLAchueQeaSNZ5oW3f044LZMz5AKBN9h42uMkhAfWsrJ9SJ+8Es1ZEtdwzh8eARjUoCPWT9Jn0Ts98Ee5NSpTeuBdlCTdA0CiFGvODpjmYtKy+e8tZZjN6qakwWUGWWHtuZsWIFly83Gr7aYHXzb3nF4tedRsD/+NfweLzGYlYViQFX+uPv2V1G60aPauphah+k0pTcXcUJnxfKIniu5gIAHTWwniljaWz49zXfjtkfI6DOAGjrdXG0UICybswNzm6paC8rif5LJZqMqsWRojV65GOnHcJDJpD/yANOfCkjECi+e84P3zfAVW6vZ2jxiU9OwXd2HWR7+VzSuDVtPhpZsiP6GEWhz1teAffu49nMuErkmv9oZLHDl8HahkFbhKH6ILgjRqyHwsA3+nqZb4m/bXv5ZguumkzmiNDMInjXI43hKceXZ8VTYrIgaEJTPL/08nY/pCTHSHSgRMhUj75YUKpUOFQIDPas1NVmgd2YYhlj1P4i4P5vPKERWJooPiJSuFIHM6apUbuUP4nkWPONcfuyaF7y68d4oYE+Tm+XL5R+czBY6Cjz0nck2RdhFrjdlCVwRFjvF0F5PXkkEpjUPTUUaJricQKzsVe+b8hyefwXtnsFuAzbRC4spUdEp/c4jBiGyYIHYI2WjwQarfdNtH92Xt0QhJgs=
    on_success: change
    on_failure: change
deploy:
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/ponyc/bintray_source.json
  skip_cleanup: true
  on:
    branch: release
    condition: $RELEASE_CONFIG == yes && -z $RELEASE_DEBS
  key:
    secure: GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/ponyc/bintray_appimage.json
  skip_cleanup: true
  on:
    branch: release
    condition: $RELEASE_CONFIG == yes && -z $RELEASE_DEBS
  key:
    secure: GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/ponyc/bintray_debian_trusty.json
  skip_cleanup: true
  on:
    branch: release
    condition: $RELEASE_CONFIG == yes && $RELEASE_DEBS == ubuntu
  key:
    secure: GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/ponyc/bintray_debian_xenial.json
  skip_cleanup: true
  on:
    branch: release
    condition: $RELEASE_CONFIG == yes && $RELEASE_DEBS == ubuntu
  key:
    secure: GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/ponyc/bintray_debian_bionic.json
  skip_cleanup: true
  on:
    branch: release
    condition: $RELEASE_CONFIG == yes && $RELEASE_DEBS == ubuntu
  key:
    secure: GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/ponyc/bintray_debian_stretch.json
  skip_cleanup: true
  on:
    branch: release
    condition: $RELEASE_CONFIG == yes && $RELEASE_DEBS == debian
  key:
    secure: GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/ponyc/bintray_debian_buster.json
  skip_cleanup: true
  on:
    branch: release
    condition: $RELEASE_CONFIG == yes && $RELEASE_DEBS == debian
  key:
    secure: GGDPvrwx0nY09smgUP0ocbBCIdvl1r96bzM7NYxxS9l9d6xGegaSFzUF6B19mdIRT4A+mR9fxpc2eQpxC6iduWVOWGwXGqtYtWzKz/C1I3s/UICPWDl2f4wsO8KGqcO2+M87aw3bwUKC4GgzKa956HKm8BVeCWhbwyFSf0c4UyST8Lkv2vAFWeRDmu/fzUwwFFpiHwlE7W1rlJhQV2xiY8pwVntgxAmTL5ssSOYdk+t65H1fIfjF3k+dU0KkARa8y2JaVhtYHlisHjCki2V3hhKenGcoK22WnNckaCM9sn/ppCm6KRhqcbtGrbEYu8XAA/xXnw3xtgZWVHhcLdTXDl13rxCGchdF1f2rtEZCfI9BSJeQlLBRrf8lF9rEdLgfUqOKSq47KKrENa5PclhGiby9iICBuzRMJxbKUvXo8dcCvFP+/Q8ekIMyAItIK/AJBX9Gx4Yv25g8n5XZDzgfNlOEou27emo7zv1/nCEZkwKQyfHAEbnpz56y0JaR+eMotBdLIHsDNZSAh+/tWNiUYBaKfZydawrnHlWxiX8diMEOqZWHhlIHRljCmt2NUxAevht2mzzoZ+NBZxfyaDcw0dt8A1cGpigZh995Pj+LaFidPK7lvIwJGJ1956Iaj+wnZxJCkCOHuTLtO5KYDTIlgbmd7vVQfX5wm9uKsrsifF8=
