language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb-src http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libllvm3.6 llvm-3.6 llvm-3.6-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install -v llvm --with-rtti; fi

script: make test && make config=release test
