version: 2.1

orbs:
  zulip: ponylang/zulip@1

jobs:
  x86-64-unknown-linux-gnu-nightly:
    docker:
      - image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    steps:
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-gnu-nightly.bash ${CLOUDSMITH_API_KEY}
      - zulip/status:
          fail_only: true

  x86-64-unknown-linux-musl-nightly:
    docker:
      - image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    steps:
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-musl-nightly.bash ${CLOUDSMITH_API_KEY}
      - zulip/status:
          fail_only: true

  x86-64-unknown-linux-gnu-release:
    docker:
      - image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    steps:
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-gnu-release.bash ${CLOUDSMITH_API_KEY}
      - zulip/status:
          fail_only: true

  x86-64-unknown-linux-musl-release:
    docker:
      - image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    steps:
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-musl-release.bash ${CLOUDSMITH_API_KEY}
      - zulip/status:
          fail_only: true

  # Docker image building
  build-release-alpine-docker-image:
      docker:
        - image: ponylang/shared-docker-ci-docker-builder:20190808
      steps:
        - checkout
        - setup_remote_docker
        - run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
        - run: bash .ci-scripts/build-alpine-docker-images-on-release.bash "$CIRCLE_TAG"
        - zulip/status:
            fail_only: true

  build-release-docker-image:
      docker:
        - image: ponylang/shared-docker-ci-docker-builder:20190808
      steps:
        - checkout
        - setup_remote_docker
        - run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
        - run: bash .ci-scripts/build-docker-images-on-release.bash "$CIRCLE_TAG"
        - zulip/status:
            fail_only: true

  # Jobs for building and testing with ponyc system installed cross-llvm
  cross-llvm-701-arm:
    docker:
      - image: ponylang/ponyc-ci:cross-llvm-7.0.1-arm
        user: pony
    steps:
      - checkout
      # build and test for x86_64 first
      - run: make config=release verbose=1 -j3 all
      - run: make config=release verbose=1 test-ci
      # build libponyrt for target arch
      - run: make config=release verbose=1 CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ arch=armv7-a tune=cortex-a9 bits=32 CFLAGS="-idirafter /usr/cross/include/" CXXFLAGS="-idirafter /usr/cross/include/" LDFLAGS="-idirafter /usr/cross/include/" PONYPATH=/usr/cross/lib -j3 libponyrt
      # build ponyc for target cross compilation
      - run: make config=release verbose=1 PONYPATH=/usr/cross/lib cross_triple=arm-unknown-linux-gnueabi cross_arch=armv7-a cross_cpu=cortex-a9 cross_linker=arm-linux-gnueabi-gcc QEMU_RUNNER="qemu-arm-static --cpu cortex-a9 -L /usr/local/arm-linux-gnueabi/libc" -j3 all
      # run tests for cross built stdlib using ponyc cross building support
      - run: make config=release verbose=1 PONYPATH=/usr/cross/lib cross_triple=arm-unknown-linux-gnueabi cross_arch=armv7-a cross_cpu=cortex-a9 cross_linker=arm-linux-gnueabi-gcc QEMU_RUNNER="qemu-arm-static --cpu cortex-a9 -L /usr/local/arm-linux-gnueabi/libc" test-cross-ci
      - zulip/status:
          fail_only: true

  cross-llvm-701-armhf:
    docker:
      - image: ponylang/ponyc-ci:cross-llvm-7.0.1-armhf
        user: pony
    steps:
      - checkout
      # build and test for x86_64 first
      - run: make config=release verbose=1 -j3 all
      - run: make config=release verbose=1 test-ci
      # build libponyrt for target arch
      - run: make config=release verbose=1 CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ arch=armv7-a tune=cortex-a9 bits=32 CFLAGS="-idirafter /usr/cross/include/" CXXFLAGS="-idirafter /usr/cross/include/" LDFLAGS="-idirafter /usr/cross/include/" PONYPATH=/usr/cross/lib -j3 libponyrt
      # build ponyc for target cross compilation
      - run: make config=release verbose=1 PONYPATH=/usr/cross/lib cross_triple=arm-unknown-linux-gnueabihf cross_arch=armv7-a cross_cpu=cortex-a9 cross_linker=arm-linux-gnueabihf-gcc QEMU_RUNNER="qemu-arm-static --cpu cortex-a9 -L /usr/local/arm-linux-gnueabihf/libc" -j3 all
      # run tests for cross built stdlib using ponyc cross building support
      - run: make config=release verbose=1 PONYPATH=/usr/cross/lib cross_triple=arm-unknown-linux-gnueabihf cross_arch=armv7-a cross_cpu=cortex-a9 cross_linker=arm-linux-gnueabihf-gcc QEMU_RUNNER="qemu-arm-static --cpu cortex-a9 -L /usr/local/arm-linux-gnueabihf/libc" test-cross-ci
      - zulip/status:
          fail_only: true

  cross-llvm-701-aarch64:
    docker:
      - image: ponylang/ponyc-ci:cross-llvm-7.0.1-aarch64
        user: pony
    steps:
      - checkout
      # build and test for x86_64 first
      - run: make config=release verbose=1 -j3 all
      - run: make config=release verbose=1 test-ci
      # build libponyrt for target arch
      - run: make config=release verbose=1 CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ arch=armv8-a tune=cortex-a53 bits=64 CFLAGS="-idirafter /usr/cross/include/" CXXFLAGS="-idirafter /usr/cross/include/" LDFLAGS="-idirafter /usr/cross/include/" PONYPATH=/usr/cross/lib -j3 libponyrt
      # build ponyc for target cross compilation
      - run: make config=release verbose=1 PONYPATH=/usr/cross/lib cross_triple=aarch64-unknown-linux-gnu cross_arch=armv8-a cross_cpu=cortex-a53 cross_linker=aarch64-linux-gnu-gcc QEMU_RUNNER="qemu-aarch64-static --cpu cortex-a53 -L /usr/local/aarch64-linux-gnu/libc" -j3 all
      # run tests for cross built stdlib using ponyc cross building support
      - run: make config=release verbose=1 PONYPATH=/usr/cross/lib cross_triple=aarch64-unknown-linux-gnu cross_arch=armv8-a cross_cpu=cortex-a53 cross_linker=aarch64-linux-gnu-gcc QEMU_RUNNER="qemu-aarch64-static --cpu cortex-a53 -L /usr/local/aarch64-linux-gnu/libc" test-cross-ci
      - zulip/status:
          fail_only: true

workflows:
  version: 2.1

  build-nightlies:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - x86-64-unknown-linux-gnu-nightly:
          context: org-global
      - x86-64-unknown-linux-musl-nightly:
          context: org-global

  # Build docker images on release
  # We don't need to build `latest` here as there's another commit
  # to master immediately after release gets kicked off that will pick
  # up all the meaningful changes. Only the TAG will be missing.
  build-release-docker-images:
    jobs:
      - build-release-alpine-docker-image:
          context: org-global
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

      - build-release-docker-image:
          context: org-global
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

  # Build release packages to upload to Cloudsmith
  build-cloudsmith-release-packages:
    jobs:
      - x86-64-unknown-linux-gnu-release:
          context: org-global
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

      - x86-64-unknown-linux-musl-release:
          context: org-global
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

  # PR acceptance tests, shouldn't run on `master` or `release` branches
  pr-acceptance-tests:
    jobs:
      # p2 cross compilation tests
      - cross-llvm-701-arm:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - release

      - cross-llvm-701-armhf:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - release

#     Currently don't pass
#      - cross-llvm-701-release-aarch64:
#           requires:
#             - lib-llvm-ubuntu-release
#           context: org-global
#          filters:
#            branches:
#              ignore:
#                - master
#                - release
#
#      - cross-llvm-701-debug-aarch64:
#           requires:
#             - lib-llvm-ubuntu-debugS
#           context: org-global
#          filters:
#            branches:
#              ignore:
#                - master
#                - release
