name: Announce a release

on:
  push:
    tags: announce-\d+.\d+.\d+

jobs:
  announce-a-release:
    name: Announce a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Announce
        uses: ponylang/release-bot-action@0.4.0
        with:
          step: announce-a-release
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          ZULIP_TOKEN: ${{ secrets.ZULIP_TOKEN }}
