name: Cloudsmith package synchronised

on:
  repository_dispatch:
    types:
      - cloudsmith-package-synchronised

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

jobs:
  send-x86-64-macos-nightly-release-event:
    if: |
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-apple-darwin.tar.gz'
    name: Send x86-64 macos nightly release event
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - ponylang/corral
          - ponylang/ponyup
    steps:
      - name: Send
        # v2.1.1
        uses: peter-evans/repository-dispatch@8324ecf35877f9b02961dd5aaf43ed7be7db9373
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: ponyc-x86_64-macos-nightly-released
          client-payload: '{"version": "${{ github.event.client_payload.data.version }}"}'
      - name: Alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  send-arm64-macos-nightly-release-event:
    if: |
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-arm64-apple-darwin.tar.gz'
    name: Send arm64 macos nightly release event
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - ponylang/corral
          - ponylang/ponyup
    steps:
      - name: Send
        # v2.1.1
        uses: peter-evans/repository-dispatch@8324ecf35877f9b02961dd5aaf43ed7be7db9373
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: ponyc-arm64-macos-nightly-released
          client-payload: '{"version": "${{ github.event.client_payload.data.version }}"}'
      - name: Alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  send-windows-nightly-release-event:
    if: |
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-pc-windows-msvc.zip'

    name: Send windows nightly release event
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - ponylang/corral
          - ponylang/http
    steps:
      - name: Send
        # v2.1.1
        uses: peter-evans/repository-dispatch@8324ecf35877f9b02961dd5aaf43ed7be7db9373
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: ponyc-windows-nightly-released
          client-payload: '{"version": "${{ github.event.client_payload.data.version }}"}'
      - name: Alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
