name: Cloudsmith package synchronised

on:
  repository_dispatch:
    types:
      - cloudsmith-package-synchronised

jobs:
  log-cloudsmith-event:
    name: Log all incoming cloudsmith events
    runs-on: ubuntu-latest
    steps:
      - name: Log event
        run: echo "$EVENT"
        env:
          EVENT: ${{ toJson(github.event) }}

  build-latest-gnu-docker-image:
    if: |
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-unknown-linux-ubuntu20.04.tar.gz'

    name: Build latest GNU Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/latest/x86-64-unknown-linux-gnu/build-and-push.bash

  build-latest-musl-docker-image:
    if: |
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-unknown-linux-musl.tar.gz'

    name: Build latest musl Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/latest/x86-64-unknown-linux-musl/build-and-push.bash

  build-latest-windows-docker-image:
    if: |
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-pc-windows-msvc.zip'

    name: Build latest Windows Docker image
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $env:DOCKER_USERNAME -p $env:DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: .dockerfiles/latest/x86-64-pc-windows-msvc/build-and-push.ps1

  build-release-gnu-docker-image:
    if: |
      github.event.client_payload.data.repository == 'releases' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-unknown-linux-ubuntu20.04.tar.gz'

    name: Build release GNU Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/release/x86-64-unknown-linux-gnu/build-and-push.bash
        env:
          VERSION: ${{ github.event.client_payload.data.version }}

  build-release-musl-docker-image:
    if: |
      github.event.client_payload.data.repository == 'releases' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-unknown-linux-musl.tar.gz'

    name: Build release musl Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/release/x86-64-unknown-linux-musl/build-and-push.bash
        env:
          VERSION: ${{ github.event.client_payload.data.version }}

  build-release-windows-docker-image:
    if: |
      github.event.client_payload.data.repository == 'releases' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-pc-windows-msvc.zip'

    name: Build release Windows Docker image
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $env:DOCKER_USERNAME -p $env:DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: .dockerfiles/release/x86-64-pc-windows-msvc/build-and-push.ps1
        env:
          VERSION: ${{ github.event.client_payload.data.version }}

  update-playground-image-on-release:
    needs:
      - build-release-musl-docker-image

    name: Update https://playground.ponylang.io/
    runs-on: ubuntu-latest
    steps:
      - name: Run remote command
        uses: ponylang-main/ssh-action@ffff33f8fe0318345a4f00f0e847325954b2a3ed
        with:
          host: ${{ secrets.PLAYGROUND_HOST }}
          username: ${{ secrets.PLAYGROUND_ADMIN_USER }}
          key: ${{ secrets.PLAYGROUND_KEY }}
          script: bash update-playground.bash

  update-stdlib-builder-image-on-release:
    needs:
      - build-release-musl-docker-image

    name: Update stdlib-builder Docker image with newly released ponyc version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-dockerfiles/stdlib-builder/build-and-push.bash

  update-stdlib-builder-image-on-nightly:
    needs:
      - build-latest-musl-docker-image

    name: Update stdlib-builder Docker image with nightly ponyc version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-dockerfiles/stdlib-builder/build-and-push.bash

  build-and-push-stdlib-documentation:
    needs:
      - update-stdlib-builder-image-on-release

    name: Build and Push standard library documentation
    runs-on: ubuntu-latest
    container:
      image: ponylang/ponyc-ci-stdlib-builder:release
    steps:
      - uses: actions/checkout@v1
      - name: Build and push
        run: "bash .ci-scripts/build-and-push-stdlib-documentation.bash $STDLIB_TOKEN"
        env:
          STDLIB_TOKEN: ${{ secrets.STDLIB_TOKEN }}

  trigger-release-announcement:
    needs:
      - build-and-push-stdlib-documentation
      - update-playground-image-on-release

    name: Trigger release announcement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger
        uses: ponylang/release-bot-action@0.5.0
        with:
          step: trigger-release-announcement
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          VERSION: ${{ github.event.client_payload.data.version }}

  send-macos-nightly-release-event:
    if: |
      github.event.client_payload.data.repository == 'nightlies' &&
      github.event.client_payload.data.name == 'ponyc-x86-64-apple-darwin.tar.gz'

    name: Send macos nightly release event
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - ponylang/ponyup
    steps:
      - name: Send
        uses: ponylang-main/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: ponyc-macos-nightly-released
          client-payload: '{}'

  send-musl-nightly-release-event:
    needs: [build-latest-musl-docker-image]

    name: Send musl nightly release event
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - ponylang/shared-docker
    steps:
      - name: Send
        uses: ponylang-main/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: ponyc-musl-nightly-released
          client-payload: '{}'

  send-musl-release-event:
    needs: [build-release-musl-docker-image]

    name: Send release event
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - ponylang/shared-docker
    steps:
      - name: Send
        uses: ponylang-main/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: ponyc-musl-released
          client-payload: '{}'
