name: Build latest Docker images

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  build-latest-docker-image:
    name: Build latest Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/x86-64-unknown-linux-gnu/build-and-push.bash

  build-latest-alpine-docker-image:
    name: Build latest Alpine based Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .dockerfiles/x86-64-unknown-linux-musl/build-and-push.bash
