name: Start a release

on:
  push:
    tags: release-*.*.*

jobs:
  start-a-release:
    name: Start a release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-release:20191107
    steps:
      - uses: actions/checkout@v1
      - name: Start release process
        run: bash .ci-scripts/release.bash
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
